### ISSUE TITLE
Class cast exception when checking server mbean

### ISSUE THREAD

**Issue by robstryker** [jolokia/jolokia#291]
!ENTRY org.eclipse.core.jobs 4 2 2016-11-01 16:02:45.695
!MESSAGE An internal error occurred during: "Connect Job".
!STACK 0
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
	at org.jolokia.client.request.ValidatingResponseExtractor.extract(ValidatingResponseExtractor.java:58)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:195)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:168)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:117)
	at org.jboss.tools.jmx.jolokia.JolokiaConnectionWrapper.verifyServerReachable(JolokiaConnectionWrapper.java:318)

This occurs when pJsonResponse is:
{"reason":"Forbidden","metadata":{},"apiVersion":"v1","code":403,"kind":"Status","details":{"kind":"pods\/proxy","name":"https:eap-app-6-9t61s:8778"},"message":"User \"openshift-dev\" cannot get pods\/proxy in project \"projName\"","status":"Failure"}

**Comment by grgrzybek** [comment]
Fixed in 5671228e
