### ISSUE TITLE
Method invocation with Date parameter is throwing IllegalArgumentException

### ISSUE THREAD

**Issue by apupier** [jolokia/jolokia#333]

**Comment by apupier** [comment]
{noformat}
org.jolokia.client.exception.J4pRemoteException: Error: java.lang.IllegalArgumentException : Mon Jul 31 13:19:11 CEST 2017
	at org.jolokia.client.request.ValidatingResponseExtractor.extract(ValidatingResponseExtractor.java:67)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:195)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:168)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:150)
{noformat}
