### ISSUE TITLE
Java 8 and Jolokia-jvm-1.6.0.jar gives (command: start) : com.sun.tools.attach.VirtualMachine

### ISSUE THREAD

**Issue by NedimT** [jolokia/jolokia#408]

**Comment by NedimT** [comment]
Can't get jolokia agent to connect to application for jmx.

I'm unable to attach the JVM agent to pid process with jmx enabled on it. Using java 1.8, java hotspot is enabled, and doing it with the same --user as the application is using, there is not password for this service Not allowed to use JDK, service is running on JRE, put tools.jar into the lib directory of JRE.

Thank you in advance!

local run of the service we are monitoring has set with below
```
-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9114 -Dcom.sun.management.jmxremote.ssl=false
```

Jolokia run command is
```
/usr/java/jre1.8.0_101/bin/java -cp /usr/java/jre1.8.0_101/lib/tools.jar:/etc/jolokia/jolokia-jvm-1.6.2-agent.jar org.jolokia.jvmagent.client.AgentLauncher start 30955
```

get below errors
```
Cannot find classes from tools.jar. The heuristics for loading tools.jar which contains
essential classes for attaching to a running JVM could locate the necessary jar file.

Please call this launcher with a qualified classpath on the command line like

   java -cp path/to/tools.jar:jolokia-jvm-1.6.2-agent.jar org.jolokia.jvmagent.client.AgentLauncher [options] <command> <ppid>
 (command: start) : com.sun.tools.attach.VirtualMachine
java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jolokia.jvmagent.client.util.ToolsClassFinder.lookupInToolsJar(ToolsClassFinder.java:83)
	at org.jolokia.jvmagent.client.util.ToolsClassFinder.lookupClass(ToolsClassFinder.java:54)
	at org.jolokia.jvmagent.client.util.VirtualMachineHandler.lookupVirtualMachineClass(VirtualMachineHandler.java:198)
	at org.jolokia.jvmagent.client.util.VirtualMachineHandler.attachVirtualMachine(VirtualMachineHandler.java:63)
	at org.jolokia.jvmagent.client.AgentLauncher.main(AgentLauncher.java:57)
```

**Comment by rhuss** [comment]
Could you please verify whether your `tools.jar` contains the class `com.sun.tools.attach.VirtualMachine` (that is required for attaching to a running process) ?

**Comment by NedimT** [comment]
Thanks for response.  I don't see the class.  Is there a Jdk version that has it that would work with java 8?
contents of tools
```
jar tvf tools-1.6.0.jar
     0 Fri Jul 20 13:13:04 PDT 2012 META-INF/
   133 Fri Jul 20 13:13:02 PDT 2012 META-INF/MANIFEST.MF
     0 Fri Jul 20 13:13:04 PDT 2012 META-INF/maven/
     0 Fri Jul 20 13:13:04 PDT 2012 META-INF/maven/com.google.api-ads/
     0 Fri Jul 20 13:13:04 PDT 2012 META-INF/maven/com.google.api-ads/tools/
  2237 Fri Jul 20 13:07:52 PDT 2012 META-INF/maven/com.google.api-ads/tools/pom.xml
   108 Fri Jul 20 13:13:02 PDT 2012 META-INF/maven/com.google.api-ads/tools/pom.properties
```

**Comment by rhuss** [comment]
So it looks like that for JRE in Java 8 you are missing the proper class files.

Jolokia is only tested on Java 8, not Java 9 or 11. There are currently no plans to upgrade, mainly because of lack of time. If someone jumps in, I would be super happy to support for all I could do in order to get Jolokia to Java 11.

**Comment by TomonoriSoejima** [comment]
using jdk-8.0.241 seems to work fine.
```
JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-8.0.241.jdk/Contents/Home" java -jar jolokia-jvm-1.6.2-agent.jar --host localhost --port 8778 start 11723

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jolokia.jvmagent.client.command.AbstractBaseCommand (file:/Users/surfer/elastic/labs/jolokia-jvm-1.6.2-agent.jar) to method sun.tools.attach.HotSpotVirtualMachine.getSystemProperties()
WARNING: Please consider reporting this to the maintainers of org.jolokia.jvmagent.client.command.AbstractBaseCommand
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jolokia is already attached to PID 11723
http://127.0.0.1:8778/jolokia/
```

**Comment by dineshbhagat** [comment]
Using `jolokia-jvm-agent-1.3.7.jar` with `openjdk version "11.0.6"` and it works fine.

**Comment by grgrzybek** [comment]
Since Jolokia 1.7.0 we have more intelligent method to call [JVM Attach API](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.attach/com/sun/tools/attach/VirtualMachine.html), so both JDK8 (reflection) and JDK9+ (module) access methods are handled.

See #394 and b30d76e9d7bdd3b9a97c857e82426ccd56616a7d
