### ISSUE TITLE
Jolokia - Origin null is not allowed to call this agent

### ISSUE THREAD

**Issue by deeniel** [jolokia/jolokia#424]
I see that since version 1.6.1 it was added the following change: 
"When strict-checking is enabled for a CORS policy, then reject a request also when no Origin or Referer header is given." 
https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/http/HttpRequestHandler.java

We use jolokia with a perl nrpe check: 
`./check_json.pl -v -u 'http://localhost:8778/jolokia/read/java.lang:type=Memory/NonHeapMemoryUsage' -a '{status}' -p '{value}->{init},{value}->{max},{value}->{used},{value}->{committed}'`

Ofc Since the origin is null, the script no longer works now. 

However I've tried to add the Origin on the header, such as localhost, 127.0.0.1 etc

```
          'error_type' => 'java.lang.Exception',
          'status' => 403,
          'stacktrace' => 'java.lang.Exception: Origin localhost is not allowed to call this agent
        at org.jolokia.http.HttpRequestHandler.handleThrowable(HttpRequestHandler.java:242)
        at org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandle(JolokiaHttpHandler.java:243)
        at org.jolokia.jvmagent.handler.JolokiaHttpHandler.handle(JolokiaHttpHandler.java:178)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
',
          'error' => 'java.lang.Exception : Origin localhost is not allowed to call this agent'
```

From my understanding, all Origin are accepted by default (except NULL now), unless you restrict them with a jolokia-access.xml file. So it should work? 

I've then tried then to create the XML file, and I've added few accepted origin, such as localhost, 127.0.0.1 but still it doesn't work. 

Any ideas/workaround? 

Thanks

**Comment by AnanyaAnandh** [comment]
Hi, I'm facing the same issue. Were you able to resolve it?

**Comment by deeniel** [comment]
Jolokia is working up to v 1.6.0 with me. I couldn't use any newer one.
This is Due to a change that was made.on v 1.6.1 in the
HttpRequestHandler.java line #286

**Comment by tadayosi** [comment]
Try sending header like this:
~~~
Origin: http://localhost:8778
~~~
instead of simply localhost.

**Comment by grgrzybek** [comment]
Yes, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
