### ISSUE TITLE
Server deadlock due to JDK 8 JUL after installing jolokia agent

### ISSUE THREAD

**Issue by wsalembi** [jolokia/jolokia#535]
Although it is not a jolokia bug, I do want to report that installing jolokia on a server can cause deadlock situations due to a bug in java.util.logging (JUL) on JDK 8. If this happens -- the timing should be really bad to reproduce this race condition -- the server hangs and never continues its boot sequence. This is quiet dangerous for production systems.

The cause is this bug in java.util.logging (JUL):
https://bugs.openjdk.org/browse/JDK-8030092
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8030092

You see the server calls java.security.Security.setProperty which initializes JUL and JolokiaStart calls sun.net.httpserver.ServerImpl.<init> which also initializes JUL.

From [JDK-8030092](https://bugs.openjdk.org/browse/JDK-8030092): Though I see the theoretical possibility for the deadlock - it does seem to be hard to trigger.
The deadlock seems to occur because LogManager.getLogManager() is called from within a synchronized lock on PlatformLogger.class. 

Our solution was to implement a DelayStartupDetector implementing ServerDetector that sleeps 3 seconds

``` 
   public void jvmAgentStartup(Instrumentation instrumentation) {
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            // ignore
        }
    }
```

This way the org.jolokia.jvmagent.JvmAgent creation of JolokiaServer is delayed a bit until after the JUL initialization.

```
                    // block until the server supporting early detection is initialized
                    awaitServerInitialization(pConfig, instrumentation);

                    server = new JolokiaServer(pConfig,pLazy);
```

It might be useful to add a -javaagent parameter to delay the jolokia startup by configuration.

DEADLOCK STACKS:

```
"JolokiaStart":
       at sun.util.logging.PlatformLogger.redirectPlatformLoggers(PlatformLogger.java:209)
       - waiting to lock <0x00000000d78c5310> ERROR   30/Nov/2022:14:51:54.757 [567f:000000000000000000000000] (a java.lang.Class for sun.util.logging.PlatformLogger)
       at java.util.logging.LogManager$3.run(LogManager.java:402)
       at java.util.logging.LogManager$3.run(LogManager.java:396)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
       - locked <0x00000000d780ed90> ERROR   30/Nov/2022:14:51:54.757 [567f:000000000000000000000000] (a java.util.logging.LogManager)
       at java.util.logging.LogManager.access$800(LogManager.java:145)
       at java.util.logging.LogManager$2.run(LogManager.java:345)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
       - locked <0x00000000d780ed90> ERROR   30/Nov/2022:14:51:54.757 [567f:000000000000000000000000] (a java.util.logging.LogManager)
       at java.util.logging.LogManager.getLogManager(LogManager.java:378)
       at java.util.logging.Logger.demandLogger(Logger.java:448)
       at java.util.logging.Logger.getLogger(Logger.java:502)
       at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:92)
       at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
       at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
       at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
       at org.jolokia.jvmagent.JolokiaServer.createHttpServer(JolokiaServer.java:238)
       at org.jolokia.jvmagent.JolokiaServer.init(JolokiaServer.java:167)
       at org.jolokia.jvmagent.JolokiaServer.<init>(JolokiaServer.java:77)
       at org.jolokia.jvmagent.JvmAgent$1.run(JvmAgent.java:98)
"main":
       at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:317)
       - waiting to lock <0x00000000d780ed90> ERROR   30/Nov/2022:14:51:54.757 [567f:000000000000000000000000] (a java.util.logging.LogManager)
       at java.util.logging.LogManager.getLogManager(LogManager.java:378)
       at java.util.logging.Logger.getPlatformLogger(Logger.java:572)
       at java.util.logging.LoggingProxyImpl.getLogger(LoggingProxyImpl.java:41)
       at sun.util.logging.LoggingSupport.getLogger(LoggingSupport.java:100)
       at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:602)
       at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:597)
       at sun.util.logging.PlatformLogger.<init>(PlatformLogger.java:239)
       at sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:198)
       - locked <0x00000000d78c5310> ERROR   30/Nov/2022:14:51:54.758 [567f:000000000000000000000000] (a java.lang.Class for sun.util.logging.PlatformLogger)
       at jdk.internal.event.EventHelper.isLoggingSecurity(EventHelper.java:138)
       at java.security.Security.setProperty(Security.java:874)
```

**Comment by grgrzybek** [comment]
See also https://bugs.openjdk.org/browse/JDK-8234466

**Comment by grgrzybek** [comment]
I see some complex logic in JDK 17's `java.util.logging.LogManager#ensureLogManagerInitialized()`, but I think the safest way would be simply to call `System.getLogger()` from pre-main of Jolokia agent.

**Comment by grgrzybek** [comment]
With extra `System.getLogger()`, I have this main thread now before starting "JolokiaStart" thread:
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.util.logging.LogManager.getLogManager(LogManager.java:430)
	  at sun.util.logging.internal.LoggingProviderImpl.demandJULLoggerFor(LoggingProviderImpl.java:409)
	  at sun.util.logging.internal.LoggingProviderImpl.demandLoggerFor(LoggingProviderImpl.java:438)
	  at jdk.internal.logger.DefaultLoggerFinder.getLogger(DefaultLoggerFinder.java:159)
	  at jdk.internal.logger.LazyLoggers.lambda$getLoggerFromFinder$0(LazyLoggers.java:413)
	  at jdk.internal.logger.LazyLoggers$$Lambda$40/0x00007fca58059a28.run(Unknown Source:-1)
	  at java.security.AccessController.executePrivileged(AccessController.java:776)
	  at java.security.AccessController.doPrivileged(AccessController.java:399)
	  at java.security.AccessController.doPrivileged(AccessController.java:460)
	  at jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:412)
	  at jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:437)
	  at java.lang.System.getLogger(System.java:1773)
	  at org.jolokia.jvmagent.JvmAgent.startAgent(JvmAgent.java:118)
	  at org.jolokia.jvmagent.JvmAgent.premain(JvmAgent.java:75)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:568)
	  at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	  at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
```
