### ISSUE TITLE
Jolokia Version 1.7.1 is not compatible with Basic Authentication Scheme implemented with Jetty Version 9.4.50

### ISSUE THREAD

**Issue by vpichura** [jolokia/jolokia#539]
When I attempted to initilize user/password for basic authentication I experienced the following error:
```
ERROR 2023-01-04 14:03:20,441 [WrapperListener_start_runner] org.mule.module.launcher.application.DefaultMuleApplication: null
java.lang.NoSuchMethodError: org.eclipse.jetty.security.HashLoginService.putUser(Ljava/lang/String;Lorg/eclipse/jetty/util/security/Credential;[Ljava/lang/String;)Lorg/eclipse/jetty/server/UserIdentity;
        at org.jolokia.mule.EclipseMuleAgentHttpServer.getLoginService(EclipseMuleAgentHttpServer.java:155) ~[jolokia-mule-1.7.1.jar:?]
        at org.jolokia.mule.EclipseMuleAgentHttpServer.getSecurityHandler(EclipseMuleAgentHttpServer.java:143) ~[jolokia-mule-1.7.1.jar:?]
        at org.jolokia.mule.EclipseMuleAgentHttpServer.getContext(EclipseMuleAgentHttpServer.java:137) ~[jolokia-mule-1.7.1.jar:?]
        at org.jolokia.mule.EclipseMuleAgentHttpServer.<init>(EclipseMuleAgentHttpServer.java:62) ~[jolokia-mule-1.7.1.jar:?]
        at org.jolokia.mule.Jetty9MuleAgentHttpServer.<init>(Jetty9MuleAgentHttpServer.java:40) ~[jolokia-mule-1.7.1.jar:?]
        at org.jolokia.mule.MuleAgentHttpServerFactory.create(MuleAgentHttpServerFactory.java:46) ~[jolokia-mule-1.7.1.jar:?]
        at org.jolokia.mule.JolokiaMuleAgent.initialise(JolokiaMuleAgent.java:116) ~[jolokia-mule-1.7.1.jar:?]
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
```

**Comment by rhuss** [comment]
This could definitely be the case, it could be that Jolokia does not run with newer Mule versions. This hasn't been checked since quite some time, happy about any pull request to address this.

**Comment by grgrzybek** [comment]
This is a problem with Mule-Jetty integration.
