### ISSUE TITLE
Improve self-generated certificate

### ISSUE THREAD

**Issue by grgrzybek** [jolokia/jolokia#556]
Currently if https is enabled, but there's no certificate, Jolokia generates one:
* reflectively using `sun.security.tools.keytool.CertAndKeyGen#getSelfCertificate()` before #394
* using custom ASN1 implementation (to be independent on things like BouncyCastle) after #394

In addition to a bug I made (not multiplying by 1000, so the certificate is valid for 4 days instead of 10 years), there are few more problems:

1. no SAN headers (cn is `Jolokia Agent 1.7.1`)
```
javax.net.ssl.SSLPeerUnverifiedException: Certificate for <localhost> doesn't match any of the subject alternative names: []
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:507)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:437)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
...
```
2. using SHA1 digest which is disabled on newer JDKs (`jdk.certpath.disabledAlgorithms` in `/etc/crypto-policies/back-ends/java.config`)
3. using PKCS12 in the first place, which is unsupported in FIPS mode

**Comment by tadayosi** [comment]
Maybe it's good time to release 1.7.3 after fixing this issue.
