### ISSUE TITLE
Hanged invocation of frontend:1.14.0:install-node-and-npm

### ISSUE THREAD

**Issue by grgrzybek** [jolokia/jolokia#593]
I'm wondering what's the problem. Trying to build client/javascript module with Maven - it gets stuck at:
```
[INFO] --- clean:3.2.0:clean (default-clean) @ jolokia-client-javascript ---
[INFO] Deleting /data/sources/github.com/jolokia/jolokia/client/javascript/target
[INFO] 
[INFO] --- source:3.3.0:jar-no-fork (default-cli) @ jolokia-client-javascript ---
[INFO] Building jar: /data/sources/github.com/jolokia/jolokia/client/javascript/target/jolokia-client-javascript-2.0.0-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- frontend:1.14.0:install-node-and-npm (install node and npm) @ jolokia-client-javascript ---
[INFO] Installing node version v18.17.1
[INFO] Downloading https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-x64.tar.gz to /home/ggrzybek/.m2/repository/com/github/eirslett/node/18.17.1/node-18.17.1-linux-x64.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
```

The thread hangs at:
```
"main" #1 prio=5 os_prio=0 cpu=4264,36ms elapsed=120,81s tid=0x00007fa650025800 nid=0x1b471 runnable  [0x00007fa6579fc000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.20/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.20/SocketInputStream.java:115)
	at java.net.SocketInputStream.read(java.base@11.0.20/SocketInputStream.java:168)
	at java.net.SocketInputStream.read(java.base@11.0.20/SocketInputStream.java:140)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@11.0.20/SSLSocketInputRecord.java:484)
	at sun.security.ssl.SSLSocketInputRecord.readHeader(java.base@11.0.20/SSLSocketInputRecord.java:478)
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(java.base@11.0.20/SSLSocketInputRecord.java:70)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(java.base@11.0.20/SSLSocketImpl.java:1334)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(java.base@11.0.20/SSLSocketImpl.java:977)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(java.base@11.0.20/Channels.java:388)
	- locked <0x000000075eea2790> (a java.lang.Object)
	at sun.nio.ch.FileChannelImpl.transferFromArbitraryChannel(java.base@11.0.20/FileChannelImpl.java:742)
	at sun.nio.ch.FileChannelImpl.transferFrom(java.base@11.0.20/FileChannelImpl.java:778)
	at com.github.eirslett.maven.plugins.frontend.lib.DefaultFileDownloader.download(FileDownloader.java:77)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.downloadFile(NodeInstaller.java:338)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.downloadFileIfMissing(NodeInstaller.java:331)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.installNodeDefault(NodeInstaller.java:141)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.install(NodeInstaller.java:95)
	- locked <0x0000000753300b88> (a java.lang.Object)
	at com.github.eirslett.maven.plugins.frontend.mojo.InstallNodeAndNpmMojo.execute(InstallNodeAndNpmMojo.java:100)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:94)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.20/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.20/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.20/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.20/Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
```

Have you seen something like this @tadayosi ?

**Comment by grgrzybek** [comment]
At some point it simply ended. Sorry for confusion ;)
