### ISSUE TITLE
Issues with flight recordings over JMX adapter

### ISSUE THREAD

**Issue by skarsaune** [jolokia/jolokia#613]
@mbazos is experiencing some issues with fligtht recordings over jolokia protocol. Based on submitted stack traces the suspect is handling of the `Recordings` attribute of the jfr bean. The supposed handling for that was added here: https://github.com/jolokia/jolokia/commit/59e3b47c051e972a3f8f2fc21aafe6db7360a3ed, however it may be sensitive to client JVM.

**Comment by grgrzybek** [comment]
Give me few days to digest all these JFR-related issues.

**Comment by skarsaune** [comment]
@mbazos I have tried running some tests with both 1.7.0, 1.7.1 and 1.7.2 and latest, without being to reproduce your specific problem. Perhaps you have stated this before, but do you have full details on context client side JVM and server side JVM?

If OK with you I would rather focus on getting the JFR PR through, perhaps followed by updating individual plugins to use latest jolokia.

**Comment by mbazos** [comment]
@skarsaune when I ran into the exception it was when I took the open source Java Mission Control from Adopt OpenJDK and installed the plugin following the documentation from Jolokia to allow a jmx connection over http. Everything worked doing this except doing a JFR recording.

Yeah I think updating the plugins to use the latest Jolokia and fix this with the latest makes a lot of sense.

**Comment by grgrzybek** [comment]
@skarsaune I'm in the process of Jolokia 2 release. After 2.0.0 is ready, I'll be looking (but January) into JMC integration and we can then cooperate (if you wish) to find any potential problems with the integration.

Thanks for your help, feedback and great https://www.youtube.com/watch?v=fg_pMpkxaSE !

**Comment by grgrzybek** [comment]
> The JSONObject don’t like the key to be any thing expect than a String.

True ;) that's what JSON is all about.... is there a chance you prepare a test case where keys are not strings?

**Comment by fbacchella** [comment]
Here it is

```
    @Test
    public void testJfrStream() throws IOException, InterruptedException {
        String host = "localhost";
        String url = "service:jmx:jolokia://" + host + ":" + port + "/jolokia/";

        JMXServiceURL u = new JMXServiceURL(url);
        JMXConnector c = JMXConnectorFactory.connect(u);
        MBeanServerConnection conn = c.getMBeanServerConnection();

        try (RemoteRecordingStream rs = new RemoteRecordingStream(conn)) {
            rs.enable("jdk.GCPhasePause").withoutThreshold();
            rs.enable("jdk.CPULoad").withPeriod(Duration.ofSeconds(1));
            rs.onEvent("jdk.CPULoad", System.out::println);
            rs.onEvent("jdk.GCPhasePause", System.out::println);
            rs.start();
            Thread.sleep(100000);
        }
    }
```

**Comment by grgrzybek** [comment]
The params we're getting in `org.jolokia.client.jmxadapter.RemoteJmxAdapter#invoke()` are:
```
    result = {java.lang.Object[2]@3805} 
     0 = {java.lang.Long@3780} 2
     1 = {javax.management.openmbean.TabularDataSupport@3734}  size = 1
      {java.util.Collections$UnmodifiableRandomAccessList@3738}  size = 1 -> {javax.management.openmbean.CompositeDataSupport@3739} "javax.management.openmbean.CompositeDataSupport(compositeType=javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)))),contents={key=name, value=Remote Recording Stream: 2025-09-04T07:13:27.399667233Z})"
       key: java.util.Collections$UnmodifiableRandomAccessList  = {java.util.Collections$UnmodifiableRandomAccessList@3738}  size = 1
        0 = {@3748} "name"
       value: javax.management.openmbean.CompositeDataSupport  = {javax.management.openmbean.CompositeDataSupport@3739} "javax.management.openmbean.CompositeDataSupport(compositeType=javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)))),contents={key=name, value=Remote Recording Stream: 2025-09-04T07:13:27.399667233Z})"
        compositeType: javax.management.openmbean.CompositeType  = {javax.management.openmbean.CompositeType@3750} "javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String))))"
         className: java.lang.String  = {@3755} "javax.management.openmbean.CompositeData"
         description: java.lang.String  = {@3756} "java.util.Map<java.lang.String, java.lang.String>"
         descriptor: javax.management.Descriptor  = null
         isArray: boolean  = false
         myHashCode: java.lang.Integer  = null
         myNamesSet: java.util.Set  = {java.util.Collections$UnmodifiableSet@3754}  size = 2
         myToString: java.lang.String  = {@3751} "javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String))))"
         nameToDescription: java.util.TreeMap  = {java.util.TreeMap@3752}  size = 2
         nameToType: java.util.TreeMap  = {java.util.TreeMap@3753}  size = 2
         typeName: java.lang.String  = {@3756} "java.util.Map<java.lang.String, java.lang.String>"
        contents: java.util.SortedMap  = {java.util.TreeMap@3749}  size = 2
         {@3758} "key" -> {@3748} "name"
         {@3759} "value" -> {@3774} "Remote Recording Stream: 2025-09-04T07:13:27.399667233Z"
```

`jdk.management.jfr.FlightRecorderMXBeanImpl#setRecordingOptions()` signature looks however more Jolokia-friendly:
```java
public void setRecordingOptions(long recording, Map<String, String> options) throws IllegalArgumentException
```

**Comment by grgrzybek** [comment]
Here's the problem described for `jolokia-client-java`:
https://github.com/jolokia/jolokia/blob/8a3823ca3a9c44511e0db1551373d0b2522b8e83/client/java/src/main/java/org/jolokia/client/request/J4pRequest.java#L183-L218

**Comment by fbacchella** [comment]
Switch from JSON to a more efficient and versatile protocol like CBOR could help resolve that. But the format is more complicated.

**Comment by grgrzybek** [comment]
Cool! https://cbor.io/
I spent last days digging inside DER encoding, so shouldn't be harder than:

> 8.19.4 The numerical value of the first subidentifier is derived from the values of the first two object identifier components in the object identifier value being encoded, using the formula:
>
>     (X*40) + Y

Protobuf could be another one.

The point is that Jolokia was always about exposing JMX through JSON over REST/HTTP. So it's implemented from the perspective of browser usage. Sure - there are binary protocols available in browser, but JSON is easiest.

**Comment by grgrzybek** [comment]
Here's how we go from JFR through MBeanPRoxy to jolokia-client-jmx-adapter:
```
	at org.jolokia.client.jmxadapter.RemoteJmxAdapter.invoke(RemoteJmxAdapter.java:445)
	at com.sun.jmx.mbeanserver.MXBeanProxy$InvokeHandler.invoke(MXBeanProxy.java:150)
	at com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
	at jdk.proxy1.$Proxy6.setRecordingOptions(Unknown Source:-1)
	at jdk.management.jfr.RemoteRecordingStream.createRecording(RemoteRecordingStream.java:287)
	at jdk.management.jfr.RemoteRecordingStream.<init>(RemoteRecordingStream.java:225)
	at jdk.management.jfr.RemoteRecordingStream.<init>(RemoteRecordingStream.java:180)
	at org.jolokia.client.jmxadapter.JfrOverJMXTest.testJfrStream(JfrOverJMXTest.java:41)
```

**Comment by grgrzybek** [comment]
`com.sun.jmx.mbeanserver.MXBeanProxy#invoke()` converts these:
```
args = {java.lang.Object[2]@4273} 
 0 = {java.lang.Long@4282} 3
 1 = {java.util.HashMap@4109}  size = 1
```

to these:
```
openArgs = {java.lang.Object[2]@4073} 
 0 = {java.lang.Long@4282} 3
 1 = {javax.management.openmbean.TabularDataSupport@3742} 
  dataMap: java.util.Map  = {java.util.LinkedHashMap@4287}  size = 1
   {java.util.Collections$UnmodifiableRandomAccessList@4052}  size = 1 -> {javax.management.openmbean.CompositeDataSupport@4053} "javax.management.openmbean.CompositeDataSupport(compositeType=javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)))),contents={key=name, value=Remote Recording Stream: 2025-09-18T07:09:19.401023265Z})"
    key: java.util.Collections$UnmodifiableRandomAccessList  = {java.util.Collections$UnmodifiableRandomAccessList@4052}  size = 1
    value: javax.management.openmbean.CompositeDataSupport  = {javax.management.openmbean.CompositeDataSupport@4053} "javax.management.openmbean.CompositeDataSupport(compositeType=javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)))),contents={key=name, value=Remote Recording Stream: 2025-09-18T07:09:19.401023265Z})"
     compositeType: javax.management.openmbean.CompositeType  = {javax.management.openmbean.CompositeType@4294} "javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String))))"
     contents: java.util.SortedMap  = {java.util.TreeMap@4321}  size = 2
      {@4290} "key" -> {@4265} "name"
      {@4306} "value" -> {@4266} "Remote Recording Stream: 2025-09-18T07:09:19.401023265Z"
  indexNamesArray: java.lang.String[]  = {java.lang.String[1]@4289} ["key"]
   0 = {@4290} "key"
  tabularType: javax.management.openmbean.TabularType  = {javax.management.openmbean.TabularType@4288} "javax.management.openmbean.TabularType(name=java.util.Map<java.lang.String, java.lang.String>,rowType=javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)))),indexNames=(key))"
   className: java.lang.String  = {@4076} "javax.management.openmbean.TabularData"
   description: java.lang.String  = {@4296} "java.util.Map<java.lang.String, java.lang.String>"
   descriptor: javax.management.Descriptor  = {javax.management.ImmutableDescriptor@4297} "{openType=javax.management.openmbean.TabularType(name=java.util.Map<java.lang.String, java.lang.String>,rowType=javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)))),indexNames=(key))}"
   indexNames: java.util.List  = {java.util.Collections$UnmodifiableRandomAccessList@4295}  size = 1
   isArray: boolean  = false
   myHashCode: java.lang.Integer  = null
   myToString: java.lang.String  = {@4291} "javax.management.openmbean.TabularType(name=java.util.Map<java.lang.String, java.lang.String>,rowType=javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)))),indexNames=(key))"
   rowType: javax.management.openmbean.CompositeType  = {javax.management.openmbean.CompositeType@4294} "javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String))))"
    className: java.lang.String  = {@4304} "javax.management.openmbean.CompositeData"
    description: java.lang.String  = {@4296} "java.util.Map<java.lang.String, java.lang.String>"
    descriptor: javax.management.Descriptor  = null
    isArray: boolean  = false
    myHashCode: java.lang.Integer  = null
    myNamesSet: java.util.Set  = {java.util.Collections$UnmodifiableSet@4303}  size = 2
     0 = {@4290} "key"
     1 = {@4306} "value"
    myToString: java.lang.String  = {@4302} "javax.management.openmbean.CompositeType(name=java.util.Map<java.lang.String, java.lang.String>,items=((itemName=key,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=value,itemType=javax.management.openmbean.SimpleType(name=java.lang.String))))"
    nameToDescription: java.util.TreeMap  = {java.util.TreeMap@4300}  size = 2
    nameToType: java.util.TreeMap  = {java.util.TreeMap@4301}  size = 2
     {@4290} "key" -> {javax.management.openmbean.SimpleType@4311} "javax.management.openmbean.SimpleType(name=java.lang.String)"
     {@4306} "value" -> {javax.management.openmbean.SimpleType@4311} "javax.management.openmbean.SimpleType(name=java.lang.String)"
    typeName: java.lang.String  = {@4296} "java.util.Map<java.lang.String, java.lang.String>"
   typeName: java.lang.String  = {@4296} "java.util.Map<java.lang.String, java.lang.String>"
```

**Comment by grgrzybek** [comment]
With this call:
```java
new ObjectToJsonConverter(new ObjectToObjectConverter(), new ObjectToOpenTypeConverter(new ObjectToObjectConverter(), false), null).serialize(pArg, new LinkedList<>(), new SerializeOptions.Builder().build())
```

I can make jolokia-client-java to produce:
```
result = {org.jolokia.json.JSONObject@4775}  size = 1
 {@4265} "name" -> {@4266} "Remote Recording Stream: 2025-09-18T07:09:19.401023265Z"
```
