### ISSUE TITLE
Error retriving metrics for jdbc statistic on glassfish

### ISSUE THREAD

**Issue by Sifcenter** [jolokia/jolokia#614]
HI,
First of all, congratulations on the project and its usefulness.

I report an error on legacy system glassfish 4.1b13, jdk 1.7.0_79-b15

GET OF http://x.x.x.x/jolokia-unsecured/read/amx:type=jdbc-connection-pool-mon,pp=*,name=resources*Derby*?ignoreErrors=true

```
{
  "error_type": "java.lang.RuntimeException",
  "error": "java.lang.RuntimeException : Invalid method on invoke",
  "status": 500,
  "request": {
    "mbean": "amx:name=resources*Derby*,pp=*,type=jdbc-connection-pool-mon",
    "type": "read"
  },
  "stacktrace": "java.lang.RuntimeException: Invalid method on invoke
	at org.glassfish.external.statistics.impl.StatisticImpl.checkMethod(StatisticImpl.java:154)
	at org.glassfish.external.statistics.impl.CountStatisticImpl.invoke(CountStatisticImpl.java:118)
	at com.sun.proxy.$Proxy114.hashCode(Unknown Source)
	at java.util.HashMap.hash(HashMap.java:362)
	at java.util.HashMap.getEntry(HashMap.java:462)
	at java.util.HashMap.get(HashMap.java:417)
	at org.glassfish.gmbal.impl.MBeanTree.getMBeanImpl(MBeanTree.java:443)
	at org.glassfish.gmbal.impl.ManagedObjectManagerImpl.getFacetAccessor(ManagedObjectManagerImpl.java:776)
	at org.glassfish.gmbal.impl.TypeConverterImpl$3.toManagedEntity(TypeConverterImpl.java:465)
	at org.glassfish.gmbal.impl.AttributeDescriptor.get(AttributeDescriptor.java:140)
	at org.glassfish.gmbal.impl.MBeanSkeleton.getAttribute(MBeanSkeleton.java:555)
	at org.glassfish.gmbal.impl.MBeanImpl.getAttribute(MBeanImpl.java:381)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at org.jolokia.handler.ReadHandler$2.execute(ReadHandler.java:60)
	at org.jolokia.backend.executor.AbstractMBeanServerExecutor.call(AbstractMBeanServerExecutor.java:90)
	at org.jolokia.handler.ReadHandler.getAttribute(ReadHandler.java:239)
	at org.jolokia.handler.ReadHandler.fetchAttributes(ReadHandler.java:189)
	at org.jolokia.handler.ReadHandler.fetchAttributesForMBeanPattern(ReadHandler.java:132)
	at org.jolokia.handler.ReadHandler.doHandleRequest(ReadHandler.java:116)
	at org.jolokia.handler.ReadHandler.doHandleRequest(ReadHandler.java:37)
	at org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:161)
	at org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:156)
	at org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:99)
	at org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:429)
	at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)
	at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)
	at org.jolokia.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:86)
	at org.jolokia.http.AgentServlet$4.handleRequest(AgentServlet.java:503)
	at org.jolokia.http.AgentServlet.handleSecurely(AgentServlet.java:383)
	at org.jolokia.http.AgentServlet.handle(AgentServlet.java:354)
	at org.jolokia.http.AgentServlet.doGet(AgentServlet.java:310)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
"
}
```
Jolokia version 1.7.2 as war deployed.

**Comment by grgrzybek** [comment]
Please give me some time to review it.

**Comment by tadayosi** [comment]
@grgrzybek For issues with 1.x, we can look at them after releasing 2.0 GA.

**Comment by grgrzybek** [comment]
I've successfully deployed Jolokia 1.7.2 in [Glassfish 4.1](http://download.oracle.com/glassfish/4.1/release/glassfish-4.1.zip) and this worked:
```
$ curl -s 'http://localhost:3000/hawtio/proxy/http/localhost/8080/jolokia-war-unsecured-1.7.2/read/amx:pp=!/domain!/resources,type=jdbc-connection-pool,name=DerbyPool/Name' | jq .
{
  "request": {
    "mbean": "amx:name=DerbyPool,pp=/domain/resources,type=jdbc-connection-pool",
    "attribute": "Name",
    "type": "read"
  },
  "value": "DerbyPool",
  "timestamp": 1745836657,
  "status": 200
}
```

Hawtio works as well:

![Image](https://github.com/user-attachments/assets/b37d2935-d8cd-4429-a1b7-ea687563972d)

If this problem still occurs (perhaps you've already moved to some newer environment?) then please reopen with more details.
