### ISSUE TITLE
RemoteJmxAdapter.isInstanceOf should handle NoClassDefFoundError, not just ClassNotFoundException 

### ISSUE THREAD

**Issue by skarsaune** [jolokia/jolokia#666]
Fix here: https://github.com/jolokia/jolokia/blob/af7075546281f65da13cd42b075bc03670f2535d/client/jmx-adapter/src/main/java/org/jolokia/client/jmxadapter/RemoteJmxAdapter.java#L595

**Comment by grgrzybek** [comment]
Thanks Martin - I'll handle it soon.

**Comment by skarsaune** [comment]
And I have also observed UnsatisfiedLinkError on Linux ..... :sweat_smile:

**Comment by skarsaune** [comment]
I may have jumped the gun. It is a chained exception. Will revert my local version to only check for NoClassDefFoundError:

> org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: Could not initialize class com.sun.management.internal.OperatingSystemImpl
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:96)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.inject(ContextInjectionFactory.java:84)
> 	at org.openjdk.jmc.console.ui.editor.internal.ConsoleEditor.doAddPages(ConsoleEditor.java:203)
> 	at org.openjdk.jmc.console.ui.editor.internal.ConsoleEditor$ConnectJob$1.run(ConsoleEditor.java:112)
> 	at org.openjdk.jmc.ui.misc.DisplayToolkit$SafeRunnable.run(DisplayToolkit.java:61)
> 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
> 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
> 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5039)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4519)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
> 	at org.openjdk.jmc.rcp.application.Application.start(Application.java:64)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
> 	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.management.internal.OperatingSystemImpl
> 	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:280)
> 	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:199)
> 	at java.management/java.lang.management.ManagementFactory.lambda$getPlatformMBeanServer$0(ManagementFactory.java:488)
> 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
> 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
> 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
> 	at java.management/java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:489)
> 	at org.openjdk.jmc.jolokia.JmcJolokiaJmxConnection.checkForLocalOperationInfo(JmcJolokiaJmxConnection.java:123)
> 	at org.openjdk.jmc.jolokia.JmcJolokiaJmxConnection.getMBeanInfo(JmcJolokiaJmxConnection.java:108)
> 	at org.openjdk.jmc.rjmx.common.internal.MCMBeanServerConnection.getMBeanInfo(MCMBeanServerConnection.java:503)
> 	at org.openjdk.jmc.rjmx.common.services.internal.HotSpot24DiagnosticCommandService.refreshOperations(HotSpot24DiagnosticCommandService.java:290)
> 	at org.openjdk.jmc.rjmx.common.services.internal.HotSpot24DiagnosticCommandService.<init>(HotSpot24DiagnosticCommandService.java:276)
> 	at org.openjdk.jmc.rjmx.common.services.internal.DiagnosticCommandServiceFactory.getServiceInstance(DiagnosticCommandServiceFactory.java:48)
> 	at org.openjdk.jmc.rjmx.common.services.internal.DiagnosticCommandServiceFactory.getServiceInstance(DiagnosticCommandServiceFactory.java:43)
> 	at org.openjdk.jmc.rjmx.common.services.internal.ServiceFactoryManager.createService(ServiceFactoryManager.java:114)
> 	at org.openjdk.jmc.rjmx.common.internal.DefaultConnectionHandle.getService(DefaultConnectionHandle.java:205)
> 	at org.openjdk.jmc.rjmx.common.internal.DefaultConnectionHandle.getServiceOrNull(DefaultConnectionHandle.java:194)
> 	at org.openjdk.jmc.console.ui.tabs.memory.HeapHistogram.create(HeapHistogram.java:273)
> 	at org.openjdk.jmc.console.ui.tabs.memory.MemoryTab.createPageContent(MemoryTab.java:115)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:132)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:94)
> 	... 30 more
> Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: 'void com.sun.management.internal.OperatingSystemImpl.initialize0()' [in thread "main"]
> 	at jdk.management/com.sun.management.internal.OperatingSystemImpl.initialize0(Native Method)
> 	at jdk.management/com.sun.management.internal.OperatingSystemImpl.<clinit>(OperatingSystemImpl.java:309)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:375)
> 	at org.jolokia.client.jmxadapter.RemoteJmxAdapter.isInstanceOf(RemoteJmxAdapter.java:569)
> 	at org.openjdk.jmc.jolokia.JmcJolokiaJmxConnection.isInstanceOf(JmcJolokiaJmxConnection.java:227)
> 	at org.openjdk.jmc.rjmx.common.internal.MCMBeanServerConnection.isInstanceOf(MCMBeanServerConnection.java:547)
> 	at java.management/java.lang.management.ManagementFactory.isInstanceOf(ManagementFactory.java:652)
> 	at java.management/java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:612)
> 	at org.openjdk.jmc.rjmx.common.ConnectionToolkit.getOperatingSystemBean(ConnectionToolkit.java:175)
> 	at org.openjdk.jmc.console.ui.tabs.system.ServerInformationModelBuilder.build(ServerInformationModelBuilder.java:126)
> 	at org.openjdk.jmc.console.ui.tabs.system.TableInformationSectionPart.<init>(TableInformationSectionPart.java:82)
> 	at org.openjdk.jmc.console.ui.tabs.system.SystemTab.createPageContent(SystemTab.java:82)
> 	... 37 more

**Comment by skarsaune** [comment]
Ah, but here is another one (Context: Opening JMX Console in Mission Control)

!ENTRY org.eclipse.ui 4 0 2024-03-28 07:26:49.592
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.UnsatisfiedLinkError: 'void com.sun.management.internal.OperatingSystemImpl.initialize0()'
	at jdk.management/com.sun.management.internal.OperatingSystemImpl.initialize0(Native Method)
	at jdk.management/com.sun.management.internal.OperatingSystemImpl.<clinit>(OperatingSystemImpl.java:309)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.jolokia.client.jmxadapter.RemoteJmxAdapter.isInstanceOf(RemoteJmxAdapter.java:569)
	at org.openjdk.jmc.jolokia.JmcJolokiaJmxConnection.isInstanceOf(JmcJolokiaJmxConnection.java:233)
	at org.openjdk.jmc.rjmx.common.internal.MCMBeanServerConnection.isInstanceOf(MCMBeanServerConnection.java:547)
	at java.management/java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:618)
	at org.openjdk.jmc.rjmx.common.ConnectionToolkit.getOperatingSystemBean(ConnectionToolkit.java:175)
	at org.openjdk.jmc.console.ui.tabs.system.ServerInformationModelBuilder.build(ServerInformationModelBuilder.java:126)
	at org.openjdk.jmc.console.ui.tabs.system.TableInformationSectionPart.<init>(TableInformationSectionPart.java:82)
	at org.openjdk.jmc.console.ui.tabs.system.SystemTab.createPageContent(SystemTab.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:132)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:94)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.inject(ContextInjectionFactory.java:84)
	at org.openjdk.jmc.console.ui.editor.internal.ConsoleEditor.doAddPages(ConsoleEditor.java:203)
	at org.openjdk.jmc.console.ui.editor.internal.ConsoleEditor$ConnectJob$1.run(ConsoleEditor.java:112)
	at org.openjdk.jmc.ui.misc.DisplayToolkit$SafeRunnable.run(DisplayToolkit.java:61)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5039)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4519)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.openjdk.jmc.rcp.application.Application.start(Application.java:64)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

**Comment by grgrzybek** [comment]
Hmm, looking at `com.sun.jmx.interceptor.DefaultMBeanServerInterceptor#isInstanceOf()` I see there's a bit more processing than simply `Class.forName()`. I believe one does not simply call `Class.forName("com.sun.management.internal.OperatingSystemImpl")` - especially with TCCLs or other env-specific config involved...

I still didn't find time to fully dig into "Jolokia 2 within JMC", so I'm not sure what's the problem and solution... But at some point I'll investigate it ;)
