### ISSUE TITLE
Alow to disable JMX detectors in config file or config options

### ISSUE THREAD

**Issue by grgrzybek** [jolokia/jolokia#698]
Artemis uses `-Djavax.management.builder.initial=org.apache.activemq.artemis.core.server.management.ArtemisMBeanServerBuilder` and some MBean interaction is impossible without proper JAAS subject.

See
* https://activemq.apache.org/components/artemis/documentation/latest/management#jmx-authorization-in-broker-xml
* [`javax.management.MBeanServerFactory#checkMBeanServerBuilder()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.management/javax/management/MBeanServerFactory.html)

While we can't make Jolokia _bypass_ the wrapper (it may not even be a wrapper), we can make Jolokia agent more flexible to allow configuration of disabled/enabled services.

**Comment by gtully** [comment]
that installs an interceptor that locks down access to the mbeanserver. any unauthenticated access (with no artemis jaas subject), like the discovery/detector processing is denied.
eg:
`E> Error while using detector GeronimoDetector: java.lang.SecurityException: AMQ229031: Unable to validate user from management. Username: null; SSL certificate subject DN: unavailable
java.lang.SecurityException: AMQ229031: Unable to validate user from management. Username: null; SSL certificate subject DN: unavailable
	at org.apache.activemq.artemis.core.server.management.ArtemisRbacInvocationHandler.securityCheck(ArtemisRbacInvocationHandler.java:207)
	at org.apache.activemq.artemis.core.server.management.ArtemisRbacInvocationHandler.invoke(ArtemisRbacInvocationHandler.java:71)
	at jdk.proxy2/jdk.proxy2.$Proxy15.queryNames(Unknown Source)
	at org.jolokia.server.core.util.jmx.DefaultMBeanServerAccess.queryNames(DefaultMBeanServerAccess.java:136)
	at org.jolokia.server.detector.jee.AbstractServerDetector.searchMBeans(AbstractServerDetector.java:94)
	at org.jolokia.server.detector.jee.AbstractServerDetector.getSingleStringAttribute(AbstractServerDetector.java:164)
	at org.jolokia.server.detector.jee.GeronimoDetector.detect(GeronimoDetector.java:43)
	at org.jolokia.server.core.service.impl.JolokiaServiceManagerImpl.detect(JolokiaServiceManagerImpl.java:310)
	at org.jolokia.server.core.service.impl.JolokiaServiceManagerImpl.start(JolokiaServiceManagerImpl.java:179)
	at org.jolokia.jvmagent.JolokiaServer.startupJolokiaContext(JolokiaServer.java:252)
	at org.jolokia.jvmagent.JolokiaServer$LazyInitializedJolokiaHttpHandler.handle(JolokiaServer.java:483)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by grgrzybek** [comment]
For now, I've added two options:
* `enabledServices` - to declare which of the detected services should be used (you have to pick all mandatory ones like `org.jolokia.service.jmx.LocalRequestHandler`, so be careful)
* `disabledServices` - to declare which of the detected services to remove (easier to use than with the above)

For example if you use `jolokia-agent-jvm` with `javaagent` classifier (which includes all services in `/META-INF/jolokia/services-default`, you can use for example:
```
disabledServices=org.jolokia.service.history.HistoryMBeanRequestInterceptor
```

if you don't want history handling.

**Comment by grgrzybek** [comment]
With `disableDetectors` option, (defaults to `false`) we can skip special server detection alltogether.

**Comment by grgrzybek** [comment]
PR: #707

**Comment by gtully** [comment]
perfect. thanks!
