### ISSUE TITLE
UndeclaredThrowableException in JMXBridgeTest

### ISSUE THREAD

**Issue by grgrzybek** [jolokia/jolokia#711]
I just got:
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jolokia.client.jmxadapter.JmxBridgeTest.testInstanceOf(JmxBridgeTest.java:423)
	at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
	at org.testng.SuiteRunner.run(SuiteRunner.java:312)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
	at org.testng.TestNG.runSuites(TestNG.java:1112)
	at org.testng.TestNG.run(TestNG.java:1079)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy1/jdk.proxy1.$Proxy44.getUsage(Unknown Source)
	... 31 more
Caused by: java.io.InvalidObjectException: Failed to invoke from(CompositeData)
	at java.management/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory.invalidObjectException(DefaultMXBeanMappingFactory.java:1531)
	at java.management/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory$CompositeBuilderViaFrom.fromCompositeData(DefaultMXBeanMappingFactory.java:1029)
	at java.management/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory$CompositeMapping.fromNonNullOpenValue(DefaultMXBeanMappingFactory.java:927)
	at java.management/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory$NonNullMXBeanMapping.fromOpenValue(DefaultMXBeanMappingFactory.java:134)
	at java.management/com.sun.jmx.mbeanserver.ConvertingMethod.fromOpenReturnValue(ConvertingMethod.java:131)
	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:168)
	at java.management/javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
	... 32 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:262)
	at java.management/com.sun.jmx.mbeanserver.DefaultMXBeanMappingFactory$CompositeBuilderViaFrom.fromCompositeData(DefaultMXBeanMappingFactory.java:1026)
	... 37 more
Caused by: java.lang.IllegalArgumentException: Unexpected composite type for MemoryUsage
	at java.management/sun.management.MemoryUsageCompositeData.validateCompositeData(MemoryUsageCompositeData.java:126)
	at java.management/java.lang.management.MemoryUsage.<init>(MemoryUsage.java:182)
	at java.management/java.lang.management.MemoryUsage.from(MemoryUsage.java:306)
	... 47 more
```

**Comment by grgrzybek** [comment]
```
memoryUsageCompositeType = {javax.management.openmbean.CompositeType@4632} "javax.management.openmbean.CompositeType(name=java.lang.management.MemoryUsage,items=((itemName=committed,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)),(itemName=init,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)),(itemName=max,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)),(itemName=used,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long))))"
 className: java.lang.String  = {@4658} "javax.management.openmbean.CompositeData"
 description: java.lang.String  = {@4664} "java.lang.management.MemoryUsage"
 descriptor: javax.management.Descriptor  = null
 isArray: boolean  = false
 myHashCode: java.lang.Integer  = null
 myNamesSet: java.util.Set  = {java.util.Collections$UnmodifiableSet@4663}  size = 4
 myToString: java.lang.String  = {@4634} "javax.management.openmbean.CompositeType(name=java.lang.management.MemoryUsage,items=((itemName=committed,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)),(itemName=init,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)),(itemName=max,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)),(itemName=used,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long))))"
 nameToDescription: java.util.TreeMap  = {java.util.TreeMap@4661}  size = 4
 nameToType: java.util.TreeMap  = {java.util.TreeMap@4662}  size = 4
  {@4671} "committed" -> {javax.management.openmbean.SimpleType@4672} "javax.management.openmbean.SimpleType(name=java.lang.Long)"
  {@4673} "init" -> {javax.management.openmbean.SimpleType@4672} "javax.management.openmbean.SimpleType(name=java.lang.Long)"
  {@4674} "max" -> {javax.management.openmbean.SimpleType@4672} "javax.management.openmbean.SimpleType(name=java.lang.Long)"
  {@4675} "used" -> {javax.management.openmbean.SimpleType@4672} "javax.management.openmbean.SimpleType(name=java.lang.Long)"
 typeName: java.lang.String  = {@4664} "java.lang.management.MemoryUsage"
```

vs.

```
result = {javax.management.openmbean.CompositeType@4639} "javax.management.openmbean.CompositeType(name=complex,items=((itemName=committed,itemType=javax.management.openmbean.SimpleType(name=java.lang.Integer)),(itemName=init,itemType=javax.management.openmbean.SimpleType(name=java.lang.Integer)),(itemName=max,itemType=javax.management.openmbean.SimpleType(name=java.lang.Integer)),(itemName=used,itemType=javax.management.openmbean.SimpleType(name=java.lang.Integer))))"
 className: java.lang.String  = {@4658} "javax.management.openmbean.CompositeData"
 description: java.lang.String  = {@4659} "complex"
 descriptor: javax.management.Descriptor  = null
 isArray: boolean  = false
 myHashCode: java.lang.Integer  = null
 myNamesSet: java.util.Set  = {java.util.Collections$UnmodifiableSet@4657}  size = 4
 myToString: java.lang.String  = {@4640} "javax.management.openmbean.CompositeType(name=complex,items=((itemName=committed,itemType=javax.management.openmbean.SimpleType(name=java.lang.Integer)),(itemName=init,itemType=javax.management.openmbean.SimpleType(name=java.lang.Integer)),(itemName=max,itemType=javax.management.openmbean.SimpleType(name=java.lang.Integer)),(itemName=used,itemType=javax.management.openmbean.SimpleType(name=java.lang.Integer))))"
 nameToDescription: java.util.TreeMap  = {java.util.TreeMap@4655}  size = 4
 nameToType: java.util.TreeMap  = {java.util.TreeMap@4656}  size = 4
  {@4647} "committed" -> {javax.management.openmbean.SimpleType@4966} "javax.management.openmbean.SimpleType(name=java.lang.Integer)"
  {@4649} "init" -> {javax.management.openmbean.SimpleType@4966} "javax.management.openmbean.SimpleType(name=java.lang.Integer)"
  {@4651} "max" -> {javax.management.openmbean.SimpleType@4966} "javax.management.openmbean.SimpleType(name=java.lang.Integer)"
  {@4653} "used" -> {javax.management.openmbean.SimpleType@4966} "javax.management.openmbean.SimpleType(name=java.lang.Integer)"
 typeName: java.lang.String  = {@4659} "complex"
```
