### ISSUE TITLE
EndpointServlet is marked as deprecated since Spring Boot 3.3

### ISSUE THREAD

**Issue by rfelgent** [jolokia/jolokia#740]
Hi,

the "jolokia-spring" integration uses the deprecated `EndpointServlet` class. Jolokia's Spring Boot integration will not be work after version 3.5 of Spring Boot (marked deprecated classes will be removed after 2 minor version upgrades)

More information about the deprecated stuff is available here https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes.

Shall I provide a merge request ?

---
Linked issues:
* spring-projects/spring-boot#31768
* spring-projects/spring-boot#20290
* hawtio/hawtio#3806

**Comment by grgrzybek** [comment]
Thanks for report - a PR would be great and I'd be happy to review it.

**Comment by rfelgent** [comment]
I'll give it a try

**Comment by grgrzybek** [comment]
At first glance I don't like this change... It's not obvious how to expose a servlet as management endpoint...

**Comment by grgrzybek** [comment]
https://docs.spring.io/spring-boot/reference/actuator/endpoints.html#actuator.endpoints.implementing-custom

**Comment by grgrzybek** [comment]
While the links at `/actuator` main page come from different endpoints, unified under single `org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver`:
```
WebMvcEndpointHandlerMapping.this.linksResolver = {org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver@9258} 
 endpoints: java.util.Collection  = {java.util.ArrayList@6765}  size = 2
  0 = {org.springframework.boot.actuate.endpoint.web.annotation.DiscoveredWebEndpoint@9278} "[DiscoveredWebEndpoint@3fdcde7a discoverer = 'org.springframework.boot.actuate.endpoint.web.annotation.WebEndpointDiscoverer', endpointBean = 'org.springframework.boot.actuate.health.HealthEndpoint']"
  1 = {org.springframework.boot.actuate.endpoint.web.annotation.DiscoveredServletEndpoint@6771} "[DiscoveredServletEndpoint@37348491 discoverer = 'org.springframework.boot.actuate.endpoint.web.annotation.ServletEndpointDiscoverer', endpointBean = 'org.jolokia.support.spring.actuator.JolokiaEndpoint']"
```

The endpoints themselves are invoked completely differently - Jolokia (servlet) endpoint is invoked bypassing Spring's `DispatcherServlet` entirely!:

```

"http-nio-8080-exec-3@8281" daemon prio=5 tid=0x22 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.jolokia.server.core.http.AgentServlet.doGet(AgentServlet.java:267)
	  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
	  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:114)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
	  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	  at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	  at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	  at java.lang.Thread.run(Thread.java:842)
```

The reason is that JolokiaEndpoint declared using `org.springframework.boot.actuate.endpoint.web.EndpointServlet` is actually registered `org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar` which is in fact `org.springframework.boot.web.servlet.ServletContextInitializer` (an abstraction over `jakarta.servlet.ServletContainerInitializer`)...

**Comment by grgrzybek** [comment]
For the record, health endpoint is invoked like this:
```
"http-nio-8080-exec-1@6823" daemon prio=5 tid=0x20 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(AbstractWebMvcEndpointHandlerMapping.java:434)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:568)
	  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:257)
	  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190)
	  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:986)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:891)
	  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1088)
	  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:978)
	  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	  at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
	  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:114)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
	  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	  at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	  at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	  at java.lang.Thread.run(Thread.java:842)
```

**Comment by grgrzybek** [comment]
Almost there.

As with the to-be-removed `org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar` I'm going to register Jolokia agent servlet using `jakarta.servlet.ServletContext#addServlet()`.
And it works, but `/actuator/jolokia` is not visible under `/actuator` _link list page_.

To make actuator mechanism aware of Jolokia endpoint (backed by servlet) we _need to_ have some bean annotated with `@WebEndpoint` with at least one `@ReadOperation` (which will never be used).

Again, I could do it easily, but I _need to_ ensure that the endpoint is registered only once in case we have different port set for management context:
```properties
management.server.port = 10001
```

In this case, `org.springframework.boot.actuate.autoconfigure.web.server.ChildManagementContextInitializer` is creating a child context for management purposes.

**Comment by grgrzybek** [comment]
For the record, here's why Spring creates two different contexts, when `management.server.port` is different: `org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration.DifferentManagementContextConfiguration`:
```java
@Configuration(proxyBeanMethods = false)
@ConditionalOnManagementPort(ManagementPortType.DIFFERENT)
static class DifferentManagementContextConfiguration {
	@Bean
	static ChildManagementContextInitializer childManagementContextInitializer(
			ManagementContextFactory managementContextFactory, AbstractApplicationContext parentContext) {
		return new ChildManagementContextInitializer(managementContextFactory, parentContext);
	}
}
```

Note: `@ConditionalOnManagementPort(ManagementPortType.DIFFERENT)`

**Comment by grgrzybek** [comment]
For the record, how Spring handles response values from `@ReadOperation` methods?
`org.springframework.boot.actuate.autoconfigure.web.servlet.CompositeHandlerAdapter#handle()` calls `org.springframework.web.servlet.HandlerAdapter#handle()` which means you can return anything - including "view name", `ModelAndView` or other Spring MVC supported objects like `org.springframework.http.RequestEntity`.
