### ISSUE TITLE
Allow env:NAME and prop:NAME expressions for all configuration properties

### ISSUE THREAD

**Issue by grgrzybek** [jolokia/jolokia#751]
Now it's only working for multicast/discovery related configuration properties.

**Comment by gtully** [comment]
this would be nice to replace 0.0.0.0 for the host when mtls is in play. with port=$(env:HOSTNAME) no joy!

`Caused by: java.lang.IllegalArgumentException: Can not lookup ${env:HOSTNAME}: java.net.UnknownHostException: ${env:HOSTNAME}: Name or service not known
 at org.jolokia.jvmagent.JolokiaServerConfig.initAddress(JolokiaServerConfig.java:603)
 at org.jolokia.jvmagent.JolokiaServerConfig.initConfigAndValidate(JolokiaServerConfig.java:365)
 at org.jolokia.jvmagent.JolokiaServerConfig.init(JolokiaServerConfig.java:115)
 at org.jolokia.jvmagent.JvmAgentConfig.<init>(JvmAgentConfig.java:60)
 at org.jolokia.jvmagent.JvmAgentConfig.<init>(JvmAgentConfig.java:45)
 at org.jolokia.jvmagent.JvmAgent.premain(JvmAgent.java:75)
 ... 6 more
Caused by: java.net.UnknownHostException: ${env:HOSTNAME}: Name or service not known
 at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
 at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
 at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
 at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
 at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
 at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
 at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
 at java.base/java.net.InetAddress.getByName(InetAddress.java:1256)
 at org.jolokia.jvmagent.JolokiaServerConfig.initAddress(JolokiaServerConfig.java:598)
 ... 11 more`

**Comment by grgrzybek** [comment]
Here's the planned order of property sources (last - highest priority that overrides all previous):

1. org.jolokia.server.core.config.ConfigKey#getDefaultValue()
2. agent/jvm/src/main/resources/default-jolokia-agent.properties (agent/jvm only)
3. arguments from "config=/path/to/file.config" file (agent/jvm)
4. arguments from remaining <options> (except "config") (agent/jvm)
5. system properties in -Djolokia.configProperty format (e.g., -Djolokia.host=0.0.0.0)
6. env variables in JOLOKIA_CONFIG_PROPERTY format

WDYT @tadayosi @gtully @rhuss ?

**Comment by grgrzybek** [comment]
After checking https://docs.spring.io/spring-boot/3.3/reference/features/external-config.html I decided to change the order a bit.
My initial assumption was that there may be container images which run some Java applications with Jolokia agent enabled using:
```
-javaagent=/path/to/jolokia.jar=port=8778,xxx=yyy,...
```

options. But in container world, what's in an image stays in a image and to change it we have to create new image `FROM existing-one`. So the option is to `podman run` existing image specifying some environment variables which are supposed to override configuration stored in the image.

I was a bit confused that Spring Boot doesn't follow this order and (roughly) uses (in inscreasing preference):
1. defaults
2. @PropertySources
3. application.properties
4. env variables
5. system properties
6. JNDI
7. servlet context
8. servlet config
9. command line

Jolokia keeps existing order of _servlet context overrides servlet context_ (IMO it should be opposite) and it's (and will be) different than Spring Boot.
But I'll change initial plan to be:

1. org.jolokia.server.core.config.ConfigKey#getDefaultValue()
2. agent/jvm/src/main/resources/default-jolokia-agent.properties (agent/jvm only)
3. servlet context params (agent/war only)
4. servlet config params (agent/war only)
5. env variables in JOLOKIA_CONFIG_PROPERTY formatDjolokia.host=0.0.0.0)
6. system properties in -Djolokia.configProperty format (e.g., -
7. arguments from "config=/path/to/file.config" file option (agent/jvm)
8. arguments from remaining (except "config") options (agent/jvm)

@gtully @tadayosi @rhuss WDYT?
