### ISSUE TITLE
Provide better error messages when Jolokia is available from two CLASSPATH entries

### ISSUE THREAD

**Issue by grgrzybek** [jolokia/jolokia#752]
It is easy to setup Jolokia JVM agent that can conflict with other type of agent - for example by adding `-javaagent` option to Artemis `etc/artemis.profile` while keeping Jolokia as WAR agent inside Artemis (Hawtio based) console.

We see the error like:
```
Caused by: java.lang.ClassCastException: class org.jolokia.service.jmx.handler.list.JDKManagementCacheKeyProvider cannot be cast to class org.jolokia.server.core.service.api.JolokiaService (org.jolokia.service.jmx.handler.list.JDKManagementCacheKeyProvider is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @1665fa54; org.jolokia.server.core.service.api.JolokiaService is in unnamed module of loader 'app')
	at org.jolokia.server.core.service.api.AbstractJolokiaService.compareTo(AbstractJolokiaService.java:27) ~[jolokia-agent-jvm-2.1.1-javaagent.jar:?]
	at java.base/java.util.TreeMap.put(TreeMap.java:814) ~[?:?]
	at java.base/java.util.TreeMap.put(TreeMap.java:534) ~[?:?]
	at java.base/java.util.TreeSet.add(TreeSet.java:255) ~[?:?]
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336) ~[?:?]
	at java.base/java.util.TreeSet.addAll(TreeSet.java:309) ~[?:?]
	at java.base/java.util.TreeSet.<init>(TreeSet.java:160) ~[?:?]
	at org.jolokia.server.core.service.impl.ClasspathServiceCreator.getServices(ClasspathServiceCreator.java:33) ~[jolokia-agent-jvm-2.1.1-javaagent.jar:?]
	at org.jolokia.server.core.service.impl.JolokiaServiceManagerImpl.addServices(JolokiaServiceManagerImpl.java:185) ~[jolokia-agent-jvm-2.1.1-javaagent.jar:?]
	at org.jolokia.server.core.http.AgentServlet.initServices(AgentServlet.java:154) ~[?:?]
	at org.jolokia.server.core.http.AgentServlet.init(AgentServlet.java:127) ~[?:?]
	at io.hawt.web.servlets.JolokiaConfiguredAgentServlet.init(JolokiaConfiguredAgentServlet.java:58) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHolder$Wrapper.init(ServletHolder.java:1305) ~[jetty-servlet-11.0.18.jar:11.0.18]
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:633) ~[jetty-servlet-11.0.18.jar:11.0.18]
	... 30 more
```

It'd be nice to detect such state and provide better error message.

**Comment by grgrzybek** [comment]
I came up with warning like this (when there's Jolokia agent running within Hawtio inside Artemis server which also starts Jolokia using `-javaagent`):
```
2024-10-29 18:11:23,611 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Service org.jolokia.service.serializer.JolokiaSerializer loaded from WebAppClassLoader{Artemis Console}@483b0690 uses incompatible JolokiaService interface
2024-10-29 18:11:23,611 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Service grgr.test.artemis2360.MyCacheKeyProvider loaded from WebAppClassLoader{Artemis Console}@483b0690 uses incompatible JolokiaService interface
2024-10-29 18:11:23,611 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Service org.jolokia.service.jmx.handler.list.JDKManagementCacheKeyProvider loaded from WebAppClassLoader{Artemis Console}@483b0690 uses incompatible JolokiaService interface
2024-10-29 18:11:23,611 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Service org.jolokia.service.jsr160.Jsr160RequestHandler loaded from WebAppClassLoader{Artemis Console}@483b0690 uses incompatible JolokiaService interface
2024-10-29 18:11:23,611 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Service grgr.test.artemis2360.MyUpdater loaded from WebAppClassLoader{Artemis Console}@483b0690 uses incompatible JolokiaService interface
2024-10-29 18:11:23,612 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Service org.jolokia.service.jmx.LocalRequestHandler loaded from WebAppClassLoader{Artemis Console}@483b0690 uses incompatible JolokiaService interface
2024-10-29 18:11:23,612 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Jolokia service discovery error - JolokiaService interface is available from multiple class loaders:
2024-10-29 18:11:23,612 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent:  - jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7
2024-10-29 18:11:23,612 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent:  - WebAppClassLoader{Artemis Console}@483b0690
2024-10-29 18:11:23,612 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Are there multiple Jolokia agents available?
2024-10-29 18:11:26,209 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Service org.jolokia.server.core.detector.FallbackServerDetector loaded from WebAppClassLoader{Artemis Console}@483b0690 uses incompatible JolokiaService interface
2024-10-29 18:11:26,210 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Jolokia service discovery error - JolokiaService interface is available from multiple class loaders:
2024-10-29 18:11:26,210 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent:  - jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7
2024-10-29 18:11:26,211 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent:  - WebAppClassLoader{Artemis Console}@483b0690
2024-10-29 18:11:26,211 WARN  [o.e.j.s.h.ContextHandler.console] jolokia-agent: Are there multiple Jolokia agents available?
```

**Comment by rhuss** [comment]
Nice :-) Maybe make the last remark about multiple Jolokia agents a bit more prominent? (like adding an empty line b. Also, I'd suggest "Possible reason: Multiple Jolokia agents are installed while only a single agent per runtime is supported"

**Comment by grgrzybek** [comment]
Thanks for suggestion - message changed ;)
