### ISSUE TITLE
Perform Jolokia initialization in privileged action

### ISSUE THREAD

**Issue by grgrzybek** [jolokia/jolokia#753]
Jolokia may run as agent in various Java applications using `-javaagent` option.
These applications may use custom MBeanServerBuilder using `-Djavax.management.builder.initial` JVM option.

ActiveMQ Artemis uses such builder (`org.apache.activemq.artemis.core.server.management.ArtemisRbacMBeanServerBuilder`) which wraps access to platform MBeanServer using `org.apache.activemq.artemis.core.server.management.ArtemisRbacInvocationHandler#ArtemisRbacInvocationHandler` which applies RBAC on every operation.

The problem is that some of the MBeanServer access is performed by Jolokia itself outside of user request threads - this is related to initialization and history.

Let's try to wrap the initialization code within `Subject.doAs()` and see how it goes.

Mind that `javax.security.auth.Subject#doAs()` is marked as deprecated and for removal, because it's (a bit) related to Java Security Manager which is in the process of removal (see https://openjdk.org/jeps/411).

Since JDK 18 we have new methods (see https://inside.java/2024/07/08/quality-heads-up/):
* `javax.security.auth.Subject#callAs()` (replacement of `Subject.doAs()`)
* `javax.security.auth.Subject#current()` (replacement of `Subject.getSubject(AccessControlContext)`)

----
Linked issues:
* https://issues.redhat.com/browse/ENTMQBR-9335

**Comment by grgrzybek** [comment]
For example we have these errors in Artemis with RBAC:

History access:
```
2024-10-15 12:46:32,905 WARN  [org.apache.activemq.artemis.core.server] AMQ222216: Security problem while authenticating: AMQ229031: Unable to validate user from management. Username: null; SSL certificate subject DN: unavailable
E> Cannot call request logger org.jolokia.service.history.HistoryMBeanRequestInterceptor@134099f5: java.lang.SecurityException: AMQ229031: Unable to validate user from management. Username: null; SSL certificate subject DN: unavailable
java.lang.SecurityException: AMQ229031: Unable to validate user from management. Username: null; SSL certificate subject DN: unavailable
	at org.apache.activemq.artemis.core.server.management.ArtemisRbacInvocationHandler.securityCheck(ArtemisRbacInvocationHandler.java:207)
	at org.apache.activemq.artemis.core.server.management.ArtemisRbacInvocationHandler.invoke(ArtemisRbacInvocationHandler.java:71)
	at jdk.proxy2/jdk.proxy2.$Proxy32.invoke(Unknown Source)
	at org.jolokia.service.history.HistoryMBeanRequestInterceptor.intercept(HistoryMBeanRequestInterceptor.java:64)
	at org.jolokia.server.core.backend.BackendManager.intercept(BackendManager.java:131)
	at org.jolokia.server.core.backend.BackendManager.handleRequest(BackendManager.java:116)
	at org.jolokia.server.core.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:207)
	at org.jolokia.server.core.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:147)
	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.executePostRequest(JolokiaHttpHandler.java:244)
	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandle(JolokiaHttpHandler.java:174)
	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.handle(JolokiaHttpHandler.java:110)
	at org.jolokia.jvmagent.JolokiaServer$LazyInitializedJolokiaHttpHandler.handle(JolokiaServer.java:487)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:853)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:820)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

Detectors:
```
2024-10-15 12:46:32,878 WARN  [org.apache.activemq.artemis.core.server] AMQ222216: Security problem while authenticating: AMQ229031: Unable to validate user from management. Username: null; SSL certificate subject DN: unavailable
E> Error while using detector ActiveMQDetector: java.lang.SecurityException: AMQ229031: Unable to validate user from management. Username: null; SSL certificate subject DN: unavailable
java.lang.SecurityException: AMQ229031: Unable to validate user from management. Username: null; SSL certificate subject DN: unavailable
	at org.apache.activemq.artemis.core.server.management.ArtemisRbacInvocationHandler.securityCheck(ArtemisRbacInvocationHandler.java:207)
	at org.apache.activemq.artemis.core.server.management.ArtemisRbacInvocationHandler.invoke(ArtemisRbacInvocationHandler.java:71)
	at jdk.proxy2/jdk.proxy2.$Proxy32.queryNames(Unknown Source)
	at org.jolokia.server.core.util.jmx.DefaultMBeanServerAccess.queryNames(DefaultMBeanServerAccess.java:137)
	at org.jolokia.server.detector.jee.AbstractServerDetector.searchMBeans(AbstractServerDetector.java:99)
	at org.jolokia.server.detector.jee.AbstractServerDetector.getSingleStringAttribute(AbstractServerDetector.java:169)
	at org.jolokia.server.detector.misc.ActiveMQDetector.detect(ActiveMQDetector.java:28)
	at org.jolokia.server.core.service.impl.JolokiaServiceManagerImpl.detect(JolokiaServiceManagerImpl.java:350)
	at org.jolokia.server.core.service.impl.JolokiaServiceManagerImpl.start(JolokiaServiceManagerImpl.java:198)
	at org.jolokia.jvmagent.JolokiaServer.startupJolokiaContext(JolokiaServer.java:252)
	at org.jolokia.jvmagent.JolokiaServer$LazyInitializedJolokiaHttpHandler.handle(JolokiaServer.java:483)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:853)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:820)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by grgrzybek** [comment]
What I need to do is to look for the places where Jolokia calls _access_ methods - mostly on `javax.management.MBeanServerConnection` interface.

For example Artemis protects these MBeanServer/MBeanServerConnection methods:
* `invoke`
* `getAttribute`
* `getAttributes`
* `setAttribute`
* `setAttributes`
* `queryMBeans`
* `queryNames`

in `org.apache.activemq.artemis.core.server.management.ArtemisRbacInvocationHandler#mBeanServerCheckedMethods`

**Comment by grgrzybek** [comment]
Jolokia uses these methods from MBeanServer/MBeanServerConnection in production (non test) code:
* javax.management.MBeanServerConnection#unregisterMBean
* javax.management.MBeanServerConnection#getObjectInstance
* javax.management.MBeanServerConnection#queryMBeans
* javax.management.MBeanServerConnection#queryNames
* javax.management.MBeanServerConnection#isRegistered
* javax.management.MBeanServerConnection#getMBeanCount
* javax.management.MBeanServerConnection#getAttribute
* javax.management.MBeanServerConnection#setAttribute
* javax.management.MBeanServerConnection#invoke
* javax.management.MBeanServerConnection#getDefaultDomain
* javax.management.MBeanServerConnection#getDomains
* javax.management.MBeanServerConnection#addNotificationListener
* javax.management.MBeanServerConnection#removeNotificationListener
* javax.management.MBeanServerConnection#getMBeanInfo
* javax.management.MBeanServer#registerMBean

We just have to carefully check which of these are called in request handling thread and which are used in initialization/configuration code.

**Comment by grgrzybek** [comment]
Now, checking with RBAC-protected Artemis, I can see:
```
result = {javax.security.auth.Subject@6911} "Subject:\n\tPrincipal: org.jolokia.server.core.auth.JolokiaAgentPrincipal@25660e9a\n"
 principals: java.util.Set  = {java.util.Collections$SynchronizedSet@6913}  size = 1
  0 = {org.jolokia.server.core.auth.JolokiaAgentPrincipal@6917} 
 privCredentials: java.util.Set  = {java.util.Collections$SynchronizedSet@6915}  size = 0
 pubCredentials: java.util.Set  = {java.util.Collections$SynchronizedSet@6914}  size = 0
 readOnly: boolean  = true
```

While the startup stack trace is:
```
"jolokia-0@6798" daemon prio=5 tid=0x45 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.jolokia.server.core.service.impl.JolokiaServiceManagerImpl.detect(JolokiaServiceManagerImpl.java:366)
	  at org.jolokia.server.core.service.impl.JolokiaServiceManagerImpl$1.run(JolokiaServiceManagerImpl.java:204)
	  at org.jolokia.server.core.service.impl.JolokiaServiceManagerImpl$1.run(JolokiaServiceManagerImpl.java:196)
	  at java.security.AccessController.executePrivileged(AccessController.java:776)
	  at java.security.AccessController.doPrivileged(AccessController.java:399)
	  at javax.security.auth.Subject.doAs(Subject.java:376)
	  at org.jolokia.server.core.service.impl.JolokiaServiceManagerImpl.start(JolokiaServiceManagerImpl.java:196)
	  - locked <0x1acb> (a org.jolokia.server.core.service.impl.JolokiaServiceManagerImpl)
	  at org.jolokia.jvmagent.JolokiaServer.startupJolokiaContext(JolokiaServer.java:252)
	  at org.jolokia.jvmagent.JolokiaServer$LazyInitializedJolokiaHttpHandler.handle(JolokiaServer.java:483)
	  - locked <0x1b38> (a org.jolokia.jvmagent.JolokiaServer$LazyInitializedJolokiaHttpHandler)
	  at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
...
```
